routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::prefix('oauth')->group(function () {
    Route::name('oauth.')->group(function () {
        Route::post('login', 'LoginController@login')->name('login');

        Route::get('personal-access-tokens', 'PersonalAccessTokenController@index');
        Route::post('personal-access-tokens', 'PersonalAccessTokenController@store');
        Route::delete('personal-access-tokens/{token_id}', 'PersonalAccessTokenController@destroy');
        Route::get('scopes', 'PersonalAccessTokenController@scopes');

        Route::get('tokens', 'TokenController@index');
        Route::delete('tokens/{token_id}', 'TokenController@destroy');

        Route::get('clients', 'ClientController@index');
        Route::post('clients', 'ClientController@store');
        Route::put('clients/{client_id}', 'ClientController@update');
        Route::delete('clients/{client_id}', 'ClientController@destroy');

        Route::post('logout', 'LoginController@logout')->name('logout');

        Route::get('redirect', 'AuthorizationController@redirect')->name('redirect');
        Route::get('callback', 'AuthorizationController@callback')->name('callback');

        Route::as('key.')->group(function () {
            Route::get('redirect/key', 'ProofKeyController@redirect')->name('redirect');
            Route::get('callback/key', 'ProofKeyController@callback')->name('callback');
        });

        Route::as('grant.')->group(function () {
            Route::get('login', 'PasswordGrantController@loginForm')->name('login');
            Route::post('request/grant', 'PasswordGrantController@request')->name('request');
        });
    });
});

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Dashboard') }}</div>

                    <div class="card-body text-center">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <a href="{{ route('oauth.redirect') }}" class="btn btn-success" target="_blank">Request Token</a>

                        <a href="{{ route('oauth.key.redirect') }}" class="btn btn-success" target="_blank">Proof Key Request</a>

                        <a href="{{ route('oauth.grant.login') }}" class="btn btn-success" target="_blank">Password Grant Request</a>
                    </div>
                </div>

                <passport-clients style="margin-top: 15px;"></passport-clients>

                <passport-authorized-clients style="margin-top: 15px;"></passport-authorized-clients>

                <passport-personal-access-tokens style="margin-top: 15px;"></passport-personal-access-tokens>
            </div>
        </div>
    </div>
@endsection

resources/views/login.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Login') }}</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-danger" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <form method="POST" action="{{ route('oauth.grant.request') }}">
                            @csrf

                            <div class="form-group row">
                                <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                                <div class="col-md-6">
                                    <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email" autofocus>

                                    @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                                <div class="col-md-6">
                                    <input id="password" type="password" class="form-control @error('email') is-invalid @enderror" name="password" value="{{ old('password') }}" required autocomplete="email" autofocus>

                                    @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-8 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Login') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection