routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::prefix('oauth')->group(function () {
    Route::name('oauth.')->group(function () {
        Route::post('login', 'LoginController@login')->name('login');

        Route::get('personal-access-tokens', 'PersonalAccessTokenController@index');
        Route::post('personal-access-tokens', 'PersonalAccessTokenController@store');
        Route::delete('personal-access-tokens/{token_id}', 'PersonalAccessTokenController@destroy');
        Route::get('scopes', 'PersonalAccessTokenController@scopes');

        Route::get('tokens', 'TokenController@index');
        Route::delete('tokens/{token_id}', 'TokenController@destroy');

        Route::get('clients', 'ClientController@index');
        Route::post('clients', 'ClientController@store');
        Route::put('clients/{client_id}', 'ClientController@update');
        Route::delete('clients/{client_id}', 'ClientController@destroy');

        Route::post('logout', 'LoginController@logout')->name('logout');

        Route::get('redirect', 'AuthorizationController@redirect')->name('redirect');
        Route::get('callback', 'AuthorizationController@callback')->name('callback');

        Route::as('key.')->group(function () {
            Route::get('redirect/key', 'ProofKeyController@redirect')->name('redirect');
            Route::get('callback/key', 'ProofKeyController@callback')->name('callback');
        });

        Route::as('grant.')->group(function () {
            Route::get('login', 'PasswordGrantController@loginForm')->name('login');
            Route::post('request/grant', 'PasswordGrantController@request')->name('request');
        });
    });
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>

        <!-- Fonts -->
        <link rel="dns-prefetch" href="//fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

        <!-- Styles -->
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    </head>
    <body>
        <div id="app">
            <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
                <div class="container">
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <!-- Left Side Of Navbar -->
                        <ul class="navbar-nav mr-auto">

                        </ul>

                        <!-- Right Side Of Navbar -->
                        <ul class="navbar-nav ml-auto">
                            <!-- Authentication Links -->
                            @token
                                <li class="nav-item dropdown">
                                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>Profile</a>

                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="{{ route('oauth.logout') }}"
                                           onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                                            {{ __('Logout') }}
                                        </a>

                                        <form id="logout-form" action="{{ route('oauth.logout') }}" method="POST" class="d-none">
                                            @csrf
                                        </form>
                                    </div>
                                </li>
                            @else
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endtoken
                        </ul>
                    </div>
                </div>
            </nav>

            <main class="py-4">
                @yield('content')
            </main>
        </div>
    </body>
</html>